### PR TITLE
Merge upstream buildcraft 1.7.10 into 1.8

### PR DESCRIPTION
**Pull request by AlexIIL**
If this works... OMFG THAT WOULD BE SOO AWESOME

### CODE REVIEW

**Comment by asiekierka** [comment]
Don't touch this. I'll try to do it myself, actually, and I will do some nice tricks in the meantime...

**Comment by AlexIIL** [comment]
Looking at git, the merge conflicts won't take that long at all to process (I would be surprised if it took longer than the weekend), but I guess whether I wait or not depends on what those tricks are.

**Comment by asiekierka** [comment]
I tried to do some tricks but I failed miserably. Go on without it.

**Comment by AlexIIL** [comment]
Out of interest, what were those tricks? I'm kinda interested now :)

**Comment by asiekierka** [comment]
Restore old pipe textures and fix the super ugly pipe shading

**Comment by AlexIIL** [comment]
Not doing this (I have 28k merge errors) so it will be ported seperatly. Also, as the 1.7.10 branch is basically staying still it will make it simpler to port forward.

**Pull request closed without merging**
